CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    full_name TEXT NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE units (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    unit_name TEXT NOT NULL
);

CREATE TABLE cocktails (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT,
    created_by TEXT,
    instructions TEXT,
    garnish TEXT,
    glass TEXT,
    notes TEXT,
    ing_instructions TEXT,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE ingredients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    instructions TEXT
);

CREATE TABLE cocktail_ing (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cocktail_id INTEGER REFERENCES cocktails(id) ON DELETE CASCADE NOT NULL,
    ingredient_id INTEGER REFERENCES ingredients(id) ON DELETE CASCADE NOT NULL,
    quantity TEXT NOT NULL,
    unit INTEGER REFERENCES units(id) ON DELETE SET NULL
);