CREATE TABLE collections (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    description TEXT,
    image_src TEXT
);

ALTER TABLE cocktails
    ADD COLUMN
        collection INTEGER REFERENCES collections(id)
        ON DELETE SET NULL,
    ADD COLUMN
        image_src TEXT;